// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlvklqpscboxkylcxmbb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdmtscXBzY2JveGt5bGN4bWJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDUxNTIsImV4cCI6MjA2NzYyMTE1Mn0.2i73T-ax3mz_eL4NYCc9jC0dvOJg9G43fB2O9SmX-3I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});